version: '3.7'

services: 
  ftp-test:
    image: fauria/vsftpd
    container_name: test_vsftpd
    environment: 
      FTP_USER: samir
      FTP_PASS: founou
    volumes: 
      - sFTP/datas:/home/vsftpd
      - docker/datalogs/vsftpd:/var/log/vsftpd/